# -*- coding: UTF-8 -*-
import bpy
import re


def t(phrase):

    language = bpy.context.preferences.view.language
    # language = bpy.types.PreferencesView.language
    
    try:
        # print(ztranslate[language][phrase])
        for key in ztranslate[language]:
            # 使用正则表达式匹配包含可变字符的键
            pattern = re.compile(re.escape(key).replace(r'\{var\}', r'(.+?)'))
            match = pattern.match(phrase)
            if match:
                return ztranslate[language][key].format(*match.groups())
        return phrase
    except KeyError:
        print(("%r: %r, #%r") % (phrase, phrase, language))
        return phrase
    except:
        return "Bug!!!@iBlender"


ztranslate = {
    "en_US": {
        "Language": "Language",
        "Buy More": "Buy More",
        "Chat Room": "Chat Room",
        "Language Description": "Language",
        "Watch online video tutorials": "Watch online video tutorials",
        "Translation is in progress. Whole text isn't translated.": "Translation is in progress. Whole text isn't translated.",  #
        "  Edge Loops Control": "  Edge Loops Control",
        "  Misc": "  Misc",
        "  Quad Size Settings": "  Quad Size Settings",
        " ERROR : no progressFile after 40s....": " ERROR : no progressFile after 40s....",
        " RETURNING ERROR.... ProgressValueFloat=": " RETURNING ERROR.... ProgressValueFloat=",
        "<<  REMESH IT >> ": "<<  REMESH IT >> ",
        "Adapt Quad Count": "Adapt Quad Count",
        "Adaptive Quad-Count :\nOn: Creates more polygons than asked to fit high curvatures area. \nOff(default): Respect the Target-Quad-Count more exactly.\nIt's advised to let it 'Off' to better respect the Target-Quad-Count. see the doc for more explanations. ": "Adaptive Quad-Count :\nOn: Creates more polygons than asked to fit high curvatures area. \nOff(default): Respect the Target-Quad-Count more exactly.\nIt's advised to let it 'Off' to better respect the Target-Quad-Count. see the doc for more explanations. ",
        "Adaptive size": "Adaptive size",
        "Allows to control how quad's size locally adapts to curvatures.\nThe higher it is, the smaller the quads will be on high curvature areas.\nSet it at 0, to get uniform quads size": "Allows to control how quad's size locally adapts to curvatures.\nThe higher it is, the smaller the quads will be on high curvature areas.\nSet it at 0, to get uniform quads size",
        "Assign new Materials to each FaceMap (using random colors) so that:\n- FaceMaps can be used with 'Use Materials' option.\n- FaceMaps can be easily visualized.": "Assign new Materials to each FaceMap (using random colors) so that:\n- FaceMaps can be used with 'Use Materials' option.\n- FaceMaps can be easily visualized.",
        "Buy More": "Buy More",
        "Cannot execute the remesher engine....": "Cannot execute the remesher engine....",
        "Chat Room": "Chat Room",
        "Defines the Color to paint to control locally the desired Quad Density variations (using 'Draw' Tool, in 'Vertex Paint' mode) \n . from 0.25 => 'divide density by 4'  =  Big Quads  =  Cyan color \n . to 4  => 'multiply density by 4'  =  Small Quads  =  Red color.": "Defines the Color to paint to control locally the desired Quad Density variations (using 'Draw' Tool, in 'Vertex Paint' mode) \n . from 0.25 => 'divide density by 4'  =  Big Quads  =  Cyan color \n . to 4  => 'multiply density by 4'  =  Small Quads  =  Red color.",
        "Detect Hard Edges by angle": "Detect Hard Edges by angle",
        "Download and install QuadRemesher Engine ?": "Download and install QuadRemesher Engine ?",
        "Downloading QuadRemesher Engine...": "Downloading QuadRemesher Engine...",
        "EXCEPTIN material_slots": "EXCEPTIN material_slots",
        "Engine not found: downloading and installing...({var})": "Engine not found: downloading and installing...({var})",
        "Error while settings LicenseManager path!": "Error while settings LicenseManager path!",
        "Face Maps 2 Materials": "Face Maps 2 Materials",
        "Failed to download Quad Remesher Engine (exception).": "Failed to download Quad Remesher Engine (exception).",
        "Failed to download Quad Remesher Engine.": "Failed to download Quad Remesher Engine.",
        "Failed to unzip Quad Remesher Engine.": "Failed to unzip Quad Remesher Engine.",
        "Hide Input Object": "Hide Input Object",
        "If On (default), the input object will be hidden after remeshing.": "If On (default), the input object will be hidden after remeshing.",
        "If On, QuadRemesher will detect/compute Hard-Edges automatically based on the geometry (using a mix of edge's angles and other geometrical considerations).\nIf 'Use Normals Splitting' is checked, it's often better to uncheck 'Detect Hard Edges by angle'.\nOn smooth organic shapes, it's advised to disable it.": "If On, QuadRemesher will detect/compute Hard-Edges automatically based on the geometry (using a mix of edge's angles and other geometrical considerations).\nIf 'Use Normals Splitting' is checked, it's often better to uncheck 'Detect Hard Edges by angle'.\nOn smooth organic shapes, it's advised to disable it.",
        "If On, QuadRemesher will use existing 'Materials' to guide the quad remeshing on Materials borders.\nMaterialIds will be maintained after remeshing.": "If On, QuadRemesher will use existing 'Materials' to guide the quad remeshing on Materials borders.\nMaterialIds will be maintained after remeshing.",
        "Language": "Language",
        "Language Description": "Language Description",
        "License Manager": "License Manager",
        "Quad Count": "Quad Count",
        "Quad Remesher ": "Quad Remesher ",
        "QuadRemesher Engine has been downloaded and installed, please click <<Remesh It>> again...": "QuadRemesher Engine has been downloaded and installed, please click <<Remesh It>> again...",
        "Quads density (paint)": "Quads density (paint)",
        "Remesh the selected mesh.": "Remesh the selected mesh.",
        "Remeshing CANCELLED !": "Remeshing CANCELLED !",
        "Remeshing FAILED !": "Remeshing FAILED !",
        "Remeshing Failed! (Bad ProgressFile Data)": "Remeshing Failed! (Bad ProgressFile Data)",
        "Remeshing Failed! (Returned without ProgressFile - 0)": "Remeshing Failed! (Returned without ProgressFile - 0)",
        "Remeshing Failed! (Returned without ProgressFile)": "Remeshing Failed! (Returned without ProgressFile)",
        "Remeshing Failed! (Stopped without result)": "Remeshing Failed! (Stopped without result)",
        "Remeshing Succeded !": "Remeshing Succeded !",
        "Remeshing progress... (ESC=Abort)": "Remeshing progress... (ESC=Abort)",
        "Remeshing progress:{var} % (ESC=Abort)": "Remeshing progress:{var} % (ESC=Abort)",
        "Remeshing with 'Use Normals Splitting' enabled and with 'Flat Shading' generally leads to poor results. You probably should switch one of them.": "Remeshing with 'Use Normals Splitting' enabled and with 'Flat Shading' generally leads to poor results. You probably should switch one of them.",
        "Reset Settings": "Reset Settings",
        "Reset settings to default values": "Reset settings to default values",
        "Settings": "Settings",
        "Symmetry:": "Symmetry:",
        "TAKE CARE: this option is usefull in specific cases, BUT should be 'Off' by default (facetted mesh). Read the doc for more informations...": "TAKE CARE: this option is usefull in specific cases, BUT should be 'Off' by default (facetted mesh). Read the doc for more informations...",
        "These options allows to perform symmetrical quad remeshing. It's possible to combine all 3 symmetry axis.": "These options allows to perform symmetrical quad remeshing. It's possible to combine all 3 symmetry axis.",
        "Translation is in progress. Whole text isn't translated.": "Translation is in progress. Whole text isn't translated.",
        "Use 'Vertex Colors' to control Quads size density.": "Use 'Vertex Colors' to control Quads size density.",
        "Use Materials": "Use Materials",
        "Use Normals Splitting": "Use Normals Splitting",
        "Use Vertex Color": "Use Vertex Color",
        "Watch online video tutorials": "Watch online video tutorials",
        "You must select one MESH object !": "You must select one MESH object !",
        "You must select one and only one object.": "You must select one and only one object.",
        "\nIf On, QuadRemesher will use the existing 'Normals' to guide the remeshing on edge loops where the normals are split/creased.\nBy default Blenders creates mesh with normals split everywhere.\nIt usefull to enable this option only with SmoothShade + AutoSmooth enabled...\nOn smooth organic shapes, it's advised to disable it.": "\nIf On, QuadRemesher will use the existing 'Normals' to guide the remeshing on edge loops where the normals are split/creased.\nBy default Blenders creates mesh with normals split everywhere.\nIt usefull to enable this option only with SmoothShade + AutoSmooth enabled...\nOn smooth organic shapes, it's advised to disable it.",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine)": "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine2)": "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine2)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrLaunch)": "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrLaunch)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrPath)": "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrPath)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=engExec)": "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=engExec)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=unzipEngine)": "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=unzipEngine)",
        "setSelectedObjectShadeFlat exception{var}\n": "setSelectedObjectShadeFlat exception{var}\n",
        "theOp.progressData.RemeshingProcess: {var}\n": "theOp.progressData.RemeshingProcess: {var}\n",
        "unzipping QuadRemesher Engine...": "unzipping QuadRemesher Engine...",
        "warning: original Materials NOT transfered to retopo !": "warning: original Materials NOT transfered to retopo !",
        "{var} Install remesher Engine ERROR: Download Failed (exception) {var}\n": "{var} Install remesher Engine ERROR: Download Failed (exception) {var}\n",
        "Set the desired number of Quads": "Set the desired number of Quads",
        "QuadRemesh": "QuadRemesh",
        "Online Help":"Online Help",
        "Opens QuadRemesher's online help in a web browser.":"Opens QuadRemesher's online help in a web browser.",
        "Check Version":"Check Version",
        "Checks whether you have the latest version of the addon or not":"Checks whether you have the latest version of the addon or not",
        "Face Sets 2 Materials":"Face Sets 2 Materials",
        "Assign new Materials to each Face Set (using random colors) so that:\n- FaceSets can be used with 'Use Materials' option.\n- FaceSets can be easily visualized.":"Assign new Materials to each Face Set (using random colors) so that:\n- FaceSets can be used with 'Use Materials' option.\n- FaceSets can be easily visualized.",
    },
    "zh_HANS": {
        "Language": "语言",
        "Chat Room": "加入 QQ 学习频道",
        "Buy More": "更新插件",
        "Language Description": "切换到中文界面时, 请在'编辑-偏好设置-界面-翻译'里取消勾选'新建数据'!!!",
        "Watch online video tutorials": "查看在线视频教程",
        "Translation is in progress. Whole text isn't translated.": "翻译进行中...",
        "  Edge Loops Control": "  循环边控制",
        "  Misc": "  杂项",
        "  Quad Size Settings": "  四边形大小设置",
        " ERROR : no progressFile after 40s....": "错误: 40 秒后文件没有进度....",
        " RETURNING ERROR.... ProgressValueFloat=": "返回错误.... ProgressValueFloat=",
        "<<  REMESH IT >> ": "<< 一键重构 >> ",
        "Adapt Quad Count": "自适应四边形数量",
        "Adaptive Quad-Count :\nOn: Creates more polygons than asked to fit high curvatures area. \nOff(default): Respect the Target-Quad-Count more exactly.\nIt's advised to let it 'Off' to better respect the Target-Quad-Count. see the doc for more explanations. ": "Adaptive Quad-Count :\n开: 创建更多的多边形以适应高曲率区域。 \n关 (默认): 目标四边形数量更准确。\n建议'关闭'以更好地获得目标四边形数量。请参阅官网文档了解更多。",
        "Adaptive size": "自适应大小",
        "Allows to control how quad's size locally adapts to curvatures.\nThe higher it is, the smaller the quads will be on high curvature areas.\nSet it at 0, to get uniform quads size": "允许控制四边形的大小如何局部适应曲率。\n越高, 四边形将在高曲率区域上越小。\n设置为 0, 以获得统一的四边形大小",
        "Assign new Materials to each FaceMap (using random colors) so that:\n- FaceMaps can be used with 'Use Materials' option.\n- FaceMaps can be easily visualized.": "分配新材质到每个面贴图 (使用随机颜色), 以便: \n- 面贴图可以与'使用材质'选项一起使用。\n- 面贴图可以很容易地可视化。",
        "Cannot execute the remesher engine....": "无法执行重构引擎....",
        "Defines the Color to paint to control locally the desired Quad Density variations (using 'Draw' Tool, in 'Vertex Paint' mode) \n . from 0.25 => 'divide density by 4'  =  Big Quads  =  Cyan color \n . to 4  => 'multiply density by 4'  =  Small Quads  =  Red color.": "定义要绘制的颜色以在本地控制所​​需的四边形密度变化(使用'绘制'工具, 在'顶点绘制'模式下)\n。从 0.25 => '将密度除以 4'  => 大四边形 = 青色 \n 。到 4  => '将密度乘以 4'  =  小四边形 = 红色。",
        "Detect Hard Edges by angle": "按角度检测硬边",
        "Download and install QuadRemesher Engine ?": "下载并安装 Quad Remesher 引擎？",
        "Downloading QuadRemesher Engine...": "下载 Quad Remesher Engine...",
        "EXCEPTIN material_slots": "意外材质槽",
        "Engine not found: downloading and installing...({var})": "未找到引擎: 正在下载和安装...{var}",
        "Error while settings LicenseManager path!": "设置许可证路径错误!",
        "Face Maps 2 Materials": "面贴图 2 材质",
        "Failed to download Quad Remesher Engine (exception).": "无法下载 Quad Remesher 引擎",
        "Failed to download Quad Remesher Engine.": "无法下载 Quad Remesher 引擎",
        "Failed to unzip Quad Remesher Engine.": "无法解压 Quad Remesher 引擎",
        "Hide Input Object": "隐藏输入对象",
        "If On (default), the input object will be hidden after remeshing.": "如果开(默认), 则在重构网格后隐藏输入对象",
        "If On, QuadRemesher will detect/compute Hard-Edges automatically based on the geometry (using a mix of edge's angles and other geometrical considerations).\nIf 'Use Normals Splitting' is checked, it's often better to uncheck 'Detect Hard Edges by angle'.\nOn smooth organic shapes, it's advised to disable it.": "如果开, Quad Remesher 将根据几何体自动检测/计算硬边(混合考量边缘角度和其它几何)。\n如果选中'使用法线拆分', 通常最好取消选中'按角度检测硬边'.\n在平滑的有机体上, 建议禁用它。",
        "If On, QuadRemesher will use existing 'Materials' to guide the quad remeshing on Materials borders.\nMaterialIds will be maintained after remeshing.": "如果开, Quad Remesher 将在材质边界上使用现有的'材质'来指导四边形重构网格。\n重构网格后将保留材质 ID",
        "License Manager": "许可证管理器",
        "Quad Count": "四边形数量",
        "Quad Remesher ": "四边形重构 ",
        "Quad Remesh": "四边形重构",
        "QuadRemesher Engine has been downloaded and installed, please click <<Remesh It>> again...": "已经下载并安装 Quad Remesher 引擎, 请再次点击<<一键重构>>...",
        "Quads density (paint)": "四边形密度(绘制)",
        "Remesh the selected mesh.": "重构所选网格。",
        "Remeshing CANCELLED !": "重构已取消 !",
        "Remeshing FAILED !": "重构失败 !",
        "Remeshing Failed! (Bad ProgressFile Data)": "重构失败! (处理文件太烂了)",
        "Remeshing Failed! (Returned without ProgressFile - 0)": "重构失败! (无处理文件而返 - 0)",
        "Remeshing Failed! (Returned without ProgressFile)": "重构失败! (无处理文件而返)",
        "Remeshing Failed! (Stopped without result)": "重构失败! (停止, 无结果)",
        "Remeshing Succeded !": "重构成功 !",
        "Remeshing progress... (ESC=Abort)": "重构进度... (ESC: 取消)",
        "Remeshing progress:{var} % (ESC=Abort)": "重构进度: {var} % (ESC: 取消)",
        "Remeshing with 'Use Normals Splitting' enabled and with 'Flat Shading' generally leads to poor results. You probably should switch one of them.": "同时使用'使用法线分割'和'扁平着色', 结果会不理想. 请只用其中的一个",
        "Reset Settings": "重置设置",
        "Reset settings to default values": "重置设置为默认值",
        "Set the desired number of Quads": "设置所需的四边形数量",
        "Settings": "设置",
        "Symmetry:": "对称性:",
        "TAKE CARE: this option is usefull in specific cases, BUT should be 'Off' by default (facetted mesh). Read the doc for more informations...": "注意: 此选项仅在特定情况下有用, 但默认情况下通常应为'关闭'(复眼网格)。阅读文档以了解更多...",
        "These options allows to perform symmetrical quad remeshing. It's possible to combine all 3 symmetry axis.": "这些选项允许执行对称四边形网格重构。可以组合所有 3 个对称轴。",
        "Use 'Vertex Colors' to control Quads size density.": "使用'顶点颜色'来控制四边形大小密度。",
        "Use Materials": "使用材质",
        "Use Normals Splitting": "使用法线分割",
        "Use Vertex Color": "使用顶点颜色",
        "You must select one MESH object !": "请选一个网格对象!",
        "You must select one and only one object.": "请仅选一个对象",
        "\nIf On, QuadRemesher will use the existing 'Normals' to guide the remeshing on edge loops where the normals are split/creased.\nBy default Blenders creates mesh with normals split everywhere.\nIt usefull to enable this option only with SmoothShade + AutoSmooth enabled...\nOn smooth organic shapes, it's advised to disable it.": "\n如果开, Quad Remesher 将使用现有的'法线'来指导在法线被分割/折痕的循环边上重构网格。\n默认情况下, Blender 会创建法线在各处分割的网格。\n在仅使用 平滑着色 + 自动平滑 情况下启用此选项很有用...\n在平滑的有机体上, 建议禁用它。",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine)": "\n卸载重装, 如何还不行, 售后咨询 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=DLengine)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine2)": "\n卸载重装, 如何还不行, 售后咨询 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=DLengine2)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrLaunch)": "\n卸载重装, 如何还不行, 售后咨询 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=LicMgrLaunch)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrPath)": "\n卸载重装, 如何还不行, 售后咨询 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=LicMgrPath)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=engExec)": "\n卸载重装, 如何还不行, 售后咨询 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=engExec)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=unzipEngine)": "\n卸载重装, 如何还不行, 售后咨询 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=unzipEngine)",
        "setSelectedObjectShadeFlat exception{var}\n": "设置所选对象扁平着色异常 {var}\n",
        "theOp.progressData.RemeshingProcess: {var}\n": "theOp.progressData.重构进程: {var}\n",
        "unzipping QuadRemesher Engine...": "解压 Quad Remesher 引擎...",
        "warning: original Materials NOT transfered to retopo !": "注意: 未转移原始材质到拓扑 !",
        "{var} Install remesher Engine ERROR: Download Failed (exception) {var}\n": "{var} 安装 remesher Engine 错误: 下载失败(异常){var}\n",
        "Online Help":"在线帮助",
        "Opens QuadRemesher's online help in a web browser.":'在网络浏览器中打开 QuadRemesher 的在线帮助。',
        "Check Version":"检查版本",
        "Checks whether you have the latest version of the addon or not":"检查您是否拥有最新版本的插件",
        "Face Sets 2 Materials":"面组 2 材料",
        "Assign new Materials to each Face Set (using random colors) so that:\n- FaceSets can be used with 'Use Materials' option.\n- FaceSets can be easily visualized.":"为每个面集分配新材质（使用随机颜色），以便：\n- FaceSet 可以与“使用材质”选项一起使用。\n- FaceSet 可以轻松可视化。",

    },
    "zh_HANT": {
        "Language": "語言",
        "Chat Room": "加入 QQ 學習頻道",
        "Buy More": "更新插件",
        "Language Description": "切換到中文界面時, 請在'編輯-偏好設置-界面-翻譯'裡取消勾選'新建數據'!!!",
        "Watch online video tutorials": "查看在線視頻教程",
        "Translation is in progress. Whole text isn't translated.": "翻譯進行中, 優化糾錯請聯繫 iBlender@taobao.com",
        "  Edge Loops Control": "  循環邊控制",
        "  Misc": "  雜項",
        "  Quad Size Settings": "  四邊形大小設置",
        " ERROR : no progressFile after 40s....": "錯誤: 40 秒後文件沒有進度....",
        " RETURNING ERROR.... ProgressValueFloat=": "返回錯誤.... ProgressValueFloat=",
        "<<  REMESH IT >> ": "<<一鍵重構>>",
        "Adapt Quad Count": "自適應四邊形數量",
        "Adaptive Quad-Count :\nOn: Creates more polygons than asked to fit high curvatures area. \nOff(default): Respect the Target-Quad-Count more exactly.\nIt's advised to let it 'Off' to better respect the Target-Quad-Count. see the doc for more explanations. ": "Adaptive Quad-Count :\n開: 創建更多的多邊形以適應高曲率區域。 \n關 (默認): 目標四邊形數量更準確。\n建議'關閉'以更好地獲得目標四邊形數量。請參閱官網文檔了解更多。",
        "Adaptive size": "自適應大小",
        "Allows to control how quad's size locally adapts to curvatures.\nThe higher it is, the smaller the quads will be on high curvature areas.\nSet it at 0, to get uniform quads size": "允許控制四邊形的大小如何局部適應曲率。\n越高, 四邊形將在高曲率區域上越小。\n設置為 0, 以獲得統一的四邊形大小",
        "Assign new Materials to each FaceMap (using random colors) so that:\n- FaceMaps can be used with 'Use Materials' option.\n- FaceMaps can be easily visualized.": "分配新材質到每個面貼圖 (使用隨機顏色), 以便: \n- 面貼圖可以與'使用材質'選項一起使用。\n- 面貼圖可以很容易地可視化。",
        "Cannot execute the remesher engine....": "無法執行重構引擎....",
        "Defines the Color to paint to control locally the desired Quad Density variations (using 'Draw' Tool, in 'Vertex Paint' mode) \n . from 0.25 => 'divide density by 4'  =  Big Quads  =  Cyan color \n . to 4  => 'multiply density by 4'  =  Small Quads  =  Red color.": "定義要繪製的顏色以在本地控制所​​需的四邊形密度變化(使用'繪製'工具, 在'頂點繪製'模式下)\n。從 0.25 => '將密度除以 4'  => 大四邊形 = 青色 \n 。到 4  => '將密度乘以 4'  =  小四邊形 = 紅色。",
        "Detect Hard Edges by angle": "按角度檢測硬邊",
        "Download and install QuadRemesher Engine ?": "下載並安裝 Quad Remesher 引擎？",
        "Downloading QuadRemesher Engine...": "下載 Quad Remesher Engine...",
        "EXCEPTIN material_slots": "意外材質槽",
        "Engine not found: downloading and installing...({var})": "未找到引擎: 正在下載和安裝...{var}",
        "Error while settings LicenseManager path!": "設置許可證路徑錯誤!",
        "Face Maps 2 Materials": "面貼圖 2 材質",
        "Failed to download Quad Remesher Engine (exception).": "無法下載 Quad Remesher 引擎",
        "Failed to download Quad Remesher Engine.": "無法下載 Quad Remesher 引擎",
        "Failed to unzip Quad Remesher Engine.": "無法解壓 Quad Remesher 引擎",
        "Hide Input Object": "隱藏輸入對象",
        "If On (default), the input object will be hidden after remeshing.": "如果開(默認), 則在重構網格後隱藏輸入對象",
        "If On, QuadRemesher will detect/compute Hard-Edges automatically based on the geometry (using a mix of edge's angles and other geometrical considerations).\nIf 'Use Normals Splitting' is checked, it's often better to uncheck 'Detect Hard Edges by angle'.\nOn smooth organic shapes, it's advised to disable it.": "如果開, Quad Remesher 將根據幾何體自動檢測/計算硬邊(混合考量邊緣角度和其它幾何)。\n如果選中'使用法線拆分', 通常最好取消選中'按角度檢測硬邊'.\n在平滑的有機體上, 建議禁用它。",
        "If On, QuadRemesher will use existing 'Materials' to guide the quad remeshing on Materials borders.\nMaterialIds will be maintained after remeshing.": "如果開, Quad Remesher 將在材質邊界上使用現有的'材質'來指導四邊形重構網格。\n重構網格後將保留材質 ID",
        "License Manager": "許可證管理器",
        "Quad Count": "四邊形數量",
        "Quad Remesher ": "四邊形重構 ",
        "Quad Remesh": "四邊形重構",
        "QuadRemesher Engine has been downloaded and installed, please click <<Remesh It>> again...": "已經下載並安裝 Quad Remesher 引擎, 請再次點擊<<一鍵重構>>...",
        "Quads density (paint)": "四邊形密度(繪製)",
        "Remesh the selected mesh.": "重構所選網格。",
        "Remeshing CANCELLED !": "重構已取消 !",
        "Remeshing FAILED !": "重構失敗 !",
        "Remeshing Failed! (Bad ProgressFile Data)": "重構失敗! (處理文件太爛了)",
        "Remeshing Failed! (Returned without ProgressFile - 0)": "重構失敗! (無處理文件而返 - 0)",
        "Remeshing Failed! (Returned without ProgressFile)": "重構失敗! (無處理文件而返)",
        "Remeshing Failed! (Stopped without result)": "重構失敗! (停止, 無結果)",
        "Remeshing Succeded !": "重構成功 !",
        "Remeshing progress... (ESC=Abort)": "重構進度... (ESC: 取消)",
        "Remeshing progress:{var} % (ESC=Abort)": "重構進度: {var} % (ESC: 取消)",
        "Remeshing with 'Use Normals Splitting' enabled and with 'Flat Shading' generally leads to poor results. You probably should switch one of them.": "同時使用'使用法線分割'和'扁平著色', 結果會不理想. 請只用其中的一個",
        "Reset Settings": "重置設置",
        "Reset settings to default values": "重置設置為默認值",
        "Set the desired number of Quads": "設置所需的四邊形數量",
        "Settings": "設置",
        "Symmetry:": "對稱性:",
        "TAKE CARE: this option is usefull in specific cases, BUT should be 'Off' by default (facetted mesh). Read the doc for more informations...": "注意: 此選項僅在特定情況下有用, 但默認情況下通常應為'關閉'(複眼網格)。閱讀文檔以了解更多...",
        "These options allows to perform symmetrical quad remeshing. It's possible to combine all 3 symmetry axis.": "這些選項允許執行對稱四邊形網格重構。可以組合所有 3 個對稱軸。",
        "Use 'Vertex Colors' to control Quads size density.": "使用'頂點顏色'來控制四邊形大小密度。",
        "Use Materials": "使用材質",
        "Use Normals Splitting": "使用法線分割",
        "Use Vertex Color": "使用頂點顏色",
        "You must select one MESH object !": "請選一個網格對象!",
        "You must select one and only one object.": "請僅選一個對象",
        "\nIf On, QuadRemesher will use the existing 'Normals' to guide the remeshing on edge loops where the normals are split/creased.\nBy default Blenders creates mesh with normals split everywhere.\nIt usefull to enable this option only with SmoothShade + AutoSmooth enabled...\nOn smooth organic shapes, it's advised to disable it.": "\n如果開, Quad Remesher 將使用現有的'法線'來指導在法線被分割/摺痕的循環邊上重構網格。\n默認情況下, Blender 會創建法線在各處分割的網格。\n在僅使用 平滑著色 + 自動平滑 情況下啟用此選項很有用...\n在平滑的有機體上, 建議禁用它。",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine)": "\n卸載重裝, 如何還不行, 售後諮詢 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=DLengine)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=DLengine2)": "\n卸載重裝, 如何還不行, 售後諮詢 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=DLengine2)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrLaunch)": "\n卸載重裝, 如何還不行, 售後諮詢 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=LicMgrLaunch)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=LicMgrPath)": "\n卸載重裝, 如何還不行, 售後諮詢 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=LicMgrPath)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=engExec)": "\n卸載重裝, 如何還不行, 售後諮詢 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=engExec)",
        "\nPlease check Trouble-Shooting section in the FAQ (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&v={var}&id=unzipEngine)": "\n卸載重裝, 如何還不行, 售後諮詢 iBlender@taobao.com (https://www.exoside.com/php_ext/qr_tsl.php?ha=Blender&amp;v={var}&amp;id=unzipEngine)",
        "setSelectedObjectShadeFlat exception{var}\n": "設置所選對象扁平著色異常 {var}\n",
        "theOp.progressData.RemeshingProcess: {var}\n": "theOp.progressData.重構進程: {var}\n",
        "unzipping QuadRemesher Engine...": "解壓 Quad Remesher 引擎...",
        "warning: original Materials NOT transfered to retopo !": "注意: 未轉移原始材質到拓撲 !",
        "{var} Install remesher Engine ERROR: Download Failed (exception) {var}\n": "{var} 安裝 remesher Engine 錯誤: 下載失敗(異常){var}\n",
        "Online Help":"線上幫助",
        "Opens QuadRemesher's online help in a web browser.":'在網頁瀏覽器中開啟 QuadRemesher 的線上說明。',
        "Check Version":"檢查版本",
        "Checks whether you have the latest version of the addon or not":"檢查您是否擁有最新版本的插件",
        "Face Sets 2 Materials":"面组 2 材料",
        "Assign new Materials to each Face Set (using random colors) so that:\n- FaceSets can be used with 'Use Materials' option.\n- FaceSets can be easily visualized.":"为每个面集分配新材质（使用随机颜色），以便：\n- FaceSet 可以与“使用材质”选项一起使用。\n- FaceSet 可以轻松可视化。",
    },
    "ja_JP": {
        "Language": "言語",
    },
    "fr_FR": {
        "Language": "Langue",
    },
    "de_DE": {
        "Language": "Sprache",
    },
    "ru_RU": {
        "Language": "Язык",
    },
    "ko_KR": {
        "Language": "언어",
    },
}
